# Site settings
title: SCHOOL FOR POETIC COMPUTATION
email: paigederaedt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reflections on my time at the School for Poetic Computation: Fall 2014
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://paigederaedt.github.io" # the base hostname & protocol for your site
twitter_username: paigederaedt
github_username:  paigederaedt

# pagnation
paginate: 10
paginate_path: "pages/page:num/"
# Build settings
markdown: kramdown
